# Generated by Django 5.2.5 on 2025-09-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
