# Generated by Django 5.2.5 on 2025-09-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_accepted',
        ),
    ]
